apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: workshop
spec:
  selector:
    app: client-deployment
  ports:
  - port: 3000  # Port exposed by the service
    protocol: TCP
  type: ClusterIP